; Generated by pymcuc for atmega328p
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ pymcu_hal__uart_avr__rx_buf, _stack_base + 0
.equ pymcu_hal__uart_avr__rx_head, _stack_base + 1
.equ pymcu_hal__uart_avr__rx_tail, _stack_base + 2
.equ pymcu_hal__timer_atmega328p__millis_count, _stack_base + 3
.equ uart, _stack_base + 7
.equ led, _stack_base + 8
.equ tmp_5, _stack_base + 10
.equ tmp_6, _stack_base + 11
.equ inline2__delay_ms_avr_i, _stack_base + 12
.equ tmp_8, _stack_base + 14
.equ tmp_11, _stack_base + 15

.org 0x0000
.global main
main:
	LDI	R16, hi8(0x08FF)
	OUT	0x3E, R16
	LDI	R16, lo8(0x08FF)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)
; main.py:12: uart = UART(9600)
	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24
; main.py:13: led = Pin("PB5", Pin.OUT)
; main.py:8: from pymcu.hal.gpio import Pin
; main.py:20:     delay_ms(500)
	LDI	R24, 1
	TST	R24
	BRNE	L_BR_SKIP_2
	RJMP	L_BIT_WRITE_SKIP_0
L_BR_SKIP_2:
	SBI	0x04, 5
	RJMP	L_BIT_WRITE_DONE_1
L_BIT_WRITE_SKIP_0:
	CBI	0x04, 5
L_BIT_WRITE_DONE_1:
; main.py:14: count: uint8 = 0
	LDI	R24, 0
	MOV	R4, R24
; main.py:16: uart.println("NOMAIN")
	LDI	R24, 21
	LDI	R25, 1
	CALL	uart_println
	MOV	R16, R24
; main.py:18: while True:
L_39:
; main.py:19:     led.high()
	CALL	led_high
	MOV	R16, R24
; main.py:20:     delay_ms(500)
; main.py:21:     led.low()
	LDI	R24, 0
	LDI	R25, 0
	STD	Y+12, R24
	STD	Y+13, R25
L_43:
	LDD	R24, Y+12
	LDD	R25, Y+13
	LDI	R18, 244
	LDI	R19, 1
	CP	R24, R18
	CPC	R25, R19
	BRLO	L_BR_SKIP_3
	RJMP	L_44
L_BR_SKIP_3:
	CALL	pymcu_time__delay_1ms_avr
	LDD	R24, Y+12
	LDD	R25, Y+13
	ADIW	R24, 1
	STD	Y+12, R24
	STD	Y+13, R25
	RJMP	L_43
L_44:
; main.py:21:     led.low()
	CALL	led_low
	MOV	R16, R24
; main.py:22:     delay_ms(500)
; main.py:21:     led.low()
	LDI	R24, 0
	LDI	R25, 0
	STD	Y+12, R24
	STD	Y+13, R25
L_47:
	LDD	R24, Y+12
	LDD	R25, Y+13
	LDI	R18, 244
	LDI	R19, 1
	CP	R24, R18
	CPC	R25, R19
	BRLO	L_BR_SKIP_4
	RJMP	L_48
L_BR_SKIP_4:
	CALL	pymcu_time__delay_1ms_avr
	LDD	R24, Y+12
	LDD	R25, Y+13
	ADIW	R24, 1
	STD	Y+12, R24
	STD	Y+13, R25
	RJMP	L_47
L_48:
; main.py:23:     count = count + 1
	INC	R4
	MOV	R24, R4
; main.py:24:     if count == 3:
	CPI	R24, 3
	BREQ	L_BR_SKIP_5
	RJMP	L_49
L_BR_SKIP_5:
; main.py:25:         uart.println("THREE")
	LDI	R24, 22
	LDI	R25, 1
	CALL	uart_println
	MOV	R16, R24
; main.py:26:         count = 0
	LDI	R24, 0
	MOV	R4, R24
L_49:
	RJMP	L_39
	RET
pymcu_time__delay_1ms_avr:
    PUSH R24
    PUSH R25
    LDI R24, 21
_dly_outer_avr:
    LDI R25, 255
_dly_inner_avr:
    DEC R25
    BRNE _dly_inner_avr
    DEC R24
    BRNE _dly_outer_avr
    POP R25
    POP R24
	RET
