; Generated by pymcuc for atmega328p
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ inline2__delay_ms_avr_i, _stack_base + 0

.org 0x0000
.global main
	RJMP	main
pymcu_time__delay_1ms_avr:
    PUSH R24
    PUSH R25
    LDI R24, 21
_dly_outer_avr:
    LDI R25, 255
_dly_inner_avr:
    DEC R25
    BRNE _dly_inner_avr
    DEC R24
    BRNE _dly_outer_avr
    POP R25
    POP R24
	RET
main:
	LDI	R16, hi8(0x08FF)
	OUT	0x3E, R16
	LDI	R16, lo8(0x08FF)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)
; main.py:11:     led = Pin("PB5", Pin.OUT)
; main.py:8: from pymcu.time import delay_ms
	LDI	R24, 1
	TST	R24
	BRNE	L_BR_SKIP_2
	RJMP	L_BIT_WRITE_SKIP_0
L_BR_SKIP_2:
	SBI	0x04, 5
	RJMP	L_BIT_WRITE_DONE_1
L_BIT_WRITE_SKIP_0:
	CBI	0x04, 5
L_BIT_WRITE_DONE_1:
; main.py:13:     while True:
L_35:
; main.py:14:         led.high()
	SBI	0x05, 5
; main.py:15:         delay_ms(1000)
	LDI	R24, 0
	LDI	R25, 0
	STD	Y+0, R24
	STD	Y+1, R25
L_40:
	LDD	R24, Y+0
	LDD	R25, Y+1
	LDI	R18, 232
	LDI	R19, 3
	CP	R24, R18
	CPC	R25, R19
	BRLO	L_BR_SKIP_3
	RJMP	L_41
L_BR_SKIP_3:
	CALL	pymcu_time__delay_1ms_avr
	LDD	R24, Y+0
	LDD	R25, Y+1
	SUBI	R24, 255
	SBCI	R25, 255
	STD	Y+0, R24
	STD	Y+1, R25
	RJMP	L_40
L_41:
; main.py:16:         led.low()
	CBI	0x05, 5
; main.py:17:         delay_ms(1000)
	LDI	R24, 0
	LDI	R25, 0
	STD	Y+0, R24
	STD	Y+1, R25
L_45:
	LDD	R24, Y+0
	LDD	R25, Y+1
	LDI	R18, 232
	LDI	R19, 3
	CP	R24, R18
	CPC	R25, R19
	BRLO	L_BR_SKIP_4
	RJMP	L_46
L_BR_SKIP_4:
	CALL	pymcu_time__delay_1ms_avr
	LDD	R24, Y+0
	LDD	R25, Y+1
	SUBI	R24, 255
	SBCI	R25, 255
	STD	Y+0, R24
	STD	Y+1, R25
	RJMP	L_45
L_46:
	RJMP	L_35
	RET
