; Generated by pymcuc for atmega328p
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ pymcu_hal__uart_avr__rx_buf, _stack_base + 0
.equ pymcu_hal__uart_avr__rx_head, _stack_base + 1
.equ pymcu_hal__uart_avr__rx_tail, _stack_base + 2
.equ pymcu_hal__timer_atmega328p__millis_count, _stack_base + 3
.equ tmp_25, _stack_base + 8
.equ inline1_write_data, _stack_base + 10
.equ tmp_28, _stack_base + 11
.equ tmp_41, _stack_base + 15
.equ tmp_44, _stack_base + 16
.equ inline2__delay_ms_avr_i, _stack_base + 21
.equ tmp_19, _stack_base + 24
.equ tmp_20, _stack_base + 25

.org 0x0000
.global main
	RJMP	main
pymcu_time__delay_1ms_avr:
    PUSH R24
    PUSH R25
    LDI R24, 21
_dly_outer_avr:
    LDI R25, 255
_dly_inner_avr:
    DEC R25
    BRNE _dly_inner_avr
    DEC R24
    BRNE _dly_outer_avr
    POP R25
    POP R24
	RET
nibble_hex:
	MOV	R4, R24
; main.py:9:     if n < 10:
	CPI	R24, 10
	BRLO	L_BR_SKIP_0
	RJMP	L_21
L_BR_SKIP_0:
; main.py:10:         return n + 48
	MOV	R24, R4
	SUBI	R24, 208
	MOV	R16, R24
	RET
L_21:
; main.py:11:     return n + 55
	MOV	R24, R4
	SUBI	R24, 201
	MOV	R16, R24
	RET
main:
	LDI	R16, hi8(0x08FF)
	OUT	0x3E, R16
	LDI	R16, lo8(0x08FF)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)
; main.py:14:     uart = UART(9600)
; main.py:27:     b: uint8 = x ^ x
; main.py:31:     uart.write('\n')
; main.py:47:     uart.write('\n')
	SBI	0x0A, 1
; main.py:48: 
	CBI	0x0A, 0
; main.py:51:     d: uint8 = (big >> 15) & 0x01
; main.py:52:     uart.write('D')
	LDI	R24, 103
	STS	0x00C4, R24
; main.py:53:     uart.write(':')
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24
; main.py:15:     uart.println("EDGE")
	LDI	R30, lo8(__str_0)
	LDI	R31, hi8(__str_0)
	CALL	__uart_send_z
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_31:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_1
	RJMP	L_32
L_BR_SKIP_1:
	RJMP	L_31
L_32:
	LDI	R24, 10
	STS	0x00C6, R24
; main.py:18:     a: uint8 = 1 << 7
	LDI	R24, 128
	MOV	R5, R24
; main.py:19:     uart.write('A')
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_35:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_2
	RJMP	L_36
L_BR_SKIP_2:
	RJMP	L_35
L_36:
	LDI	R24, 65
	STS	0x00C6, R24
; main.py:20:     uart.write(':')
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_39:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_3
	RJMP	L_40
L_BR_SKIP_3:
	RJMP	L_39
L_40:
	LDI	R24, 58
	STS	0x00C6, R24
; main.py:21:     uart.write(nibble_hex(a >> 4))
	MOV	R24, R5
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	MOV	R16, R24
	MOV	R4, R24
	CALL	nibble_hex
	STD	Y+10, R24
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_43:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_4
	RJMP	L_44
L_BR_SKIP_4:
	RJMP	L_43
L_44:
	LDD	R24, Y+10
	STS	0x00C6, R24
; main.py:22:     uart.write(nibble_hex(a & 0xF))
	MOV	R24, R5
	ANDI	R24, 15
	MOV	R16, R24
	MOV	R4, R24
	CALL	nibble_hex
	STD	Y+10, R24
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_47:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_5
	RJMP	L_48
L_BR_SKIP_5:
	RJMP	L_47
L_48:
	LDD	R24, Y+10
	STS	0x00C6, R24
; main.py:23:     uart.write('\n')
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_51:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_6
	RJMP	L_52
L_BR_SKIP_6:
	RJMP	L_51
L_52:
	LDI	R24, 10
	STS	0x00C6, R24
; main.py:26:     x: uint8 = 0xAB
	LDI	R24, 171
	MOV	R9, R24
; main.py:27:     b: uint8 = x ^ x
	LDI	R24, 0
	MOV	R6, R24
; main.py:28:     uart.write('B')
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_55:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_7
	RJMP	L_56
L_BR_SKIP_7:
	RJMP	L_55
L_56:
	LDI	R24, 66
	STS	0x00C6, R24
; main.py:29:     uart.write(':')
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_59:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_8
	RJMP	L_60
L_BR_SKIP_8:
	RJMP	L_59
L_60:
	LDI	R24, 58
	STS	0x00C6, R24
; main.py:30:     uart.write(nibble_hex(b))
	MOV	R24, R6
	MOV	R4, R24
	CALL	nibble_hex
	STD	Y+10, R24
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_63:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_9
	RJMP	L_64
L_BR_SKIP_9:
	RJMP	L_63
L_64:
	LDD	R24, Y+10
	STS	0x00C6, R24
; main.py:31:     uart.write('\n')
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_67:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_10
	RJMP	L_68
L_BR_SKIP_10:
	RJMP	L_67
L_68:
	LDI	R24, 10
	STS	0x00C6, R24
; main.py:34:     c: uint8 = 0xCD & 0xFF
	LDI	R24, 205
	MOV	R7, R24
; main.py:35:     uart.write('C')
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_71:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_11
	RJMP	L_72
L_BR_SKIP_11:
	RJMP	L_71
L_72:
	LDI	R24, 67
	STS	0x00C6, R24
; main.py:36:     uart.write(':')
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_75:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_12
	RJMP	L_76
L_BR_SKIP_12:
	RJMP	L_75
L_76:
	LDI	R24, 58
	STS	0x00C6, R24
; main.py:37:     uart.write(nibble_hex(c >> 4))
	MOV	R24, R7
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	MOV	R16, R24
	MOV	R4, R24
	CALL	nibble_hex
	STD	Y+10, R24
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_79:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_13
	RJMP	L_80
L_BR_SKIP_13:
	RJMP	L_79
L_80:
	LDD	R24, Y+10
	STS	0x00C6, R24
; main.py:38:     uart.write(nibble_hex(c & 0xF))
	MOV	R24, R7
	ANDI	R24, 15
	MOV	R16, R24
	MOV	R4, R24
	CALL	nibble_hex
	STD	Y+10, R24
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_83:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_14
	RJMP	L_84
L_BR_SKIP_14:
	RJMP	L_83
L_84:
	LDD	R24, Y+10
	STS	0x00C6, R24
; main.py:39:     uart.write('\n')
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_87:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_15
	RJMP	L_88
L_BR_SKIP_15:
	RJMP	L_87
L_88:
	LDI	R24, 10
	STS	0x00C6, R24
; main.py:42:     z: uint8 = 0
	LDI	R24, 0
	MOV	R10, R24
; main.py:43:     if z < 1:
	CPI	R24, 1
	BRLO	L_BR_SKIP_16
	RJMP	L_90
L_BR_SKIP_16:
; main.py:44:         uart.write('T')
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_93:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_17
	RJMP	L_94
L_BR_SKIP_17:
	RJMP	L_93
L_94:
	LDI	R24, 84
	STS	0x00C6, R24
	RJMP	L_89
L_90:
; main.py:46:         uart.write('F')
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_97:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_18
	RJMP	L_98
L_BR_SKIP_18:
	RJMP	L_97
L_98:
	LDI	R24, 70
	STS	0x00C6, R24
L_89:
; main.py:47:     uart.write('\n')
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_101:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_19
	RJMP	L_102
L_BR_SKIP_19:
	RJMP	L_101
L_102:
	LDI	R24, 10
	STS	0x00C6, R24
; main.py:50:     big: uint16 = 0x8000
	LDI	R24, 0
	LDI	R25, 128
	MOV	R11, R24
	MOV	R12, R25
; main.py:51:     d: uint8 = (big >> 15) & 0x01
	LDI	R24, 1
	MOV	R8, R24
; main.py:52:     uart.write('D')
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_105:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_20
	RJMP	L_106
L_BR_SKIP_20:
	RJMP	L_105
L_106:
	LDI	R24, 68
	STS	0x00C6, R24
; main.py:53:     uart.write(':')
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_109:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_21
	RJMP	L_110
L_BR_SKIP_21:
	RJMP	L_109
L_110:
	LDI	R24, 58
	STS	0x00C6, R24
; main.py:54:     uart.write(nibble_hex(d))
	MOV	R24, R8
	MOV	R4, R24
	CALL	nibble_hex
	STD	Y+10, R24
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_113:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_22
	RJMP	L_114
L_BR_SKIP_22:
	RJMP	L_113
L_114:
	LDD	R24, Y+10
	STS	0x00C6, R24
; main.py:55:     uart.write('\n')
; main.py:41:     # Zero comparison: 0 < 1 = true (send T)
; main.py:45:     else:
L_117:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_23
	RJMP	L_118
L_BR_SKIP_23:
	RJMP	L_117
L_118:
	LDI	R24, 10
	STS	0x00C6, R24
; main.py:57:     while True:
L_119:
; main.py:58:         delay_ms(1000)
; main.py:21:     uart.write(nibble_hex(a >> 4))
; main.py:30:     uart.write(nibble_hex(b))
	LDI	R24, 0
	LDI	R25, 0
	STD	Y+21, R24
	STD	Y+22, R25
L_123:
	LDD	R24, Y+21
	LDD	R25, Y+22
	LDI	R18, 232
	LDI	R19, 3
	CP	R24, R18
	CPC	R25, R19
	BRLO	L_BR_SKIP_24
	RJMP	L_124
L_BR_SKIP_24:
	CALL	pymcu_time__delay_1ms_avr
	LDD	R24, Y+21
	LDD	R25, Y+22
	ADIW	R24, 1
	STD	Y+21, R24
	STD	Y+22, R25
	RJMP	L_123
L_124:
	RJMP	L_119
	RET

; --- Flash String Pool (LPM+Z UART send) ---
__uart_send_z:
__usendz_loop:
	LPM	R24, Z+
	TST	R24
	BREQ	__usendz_done
__usendz_wait:
	LDS	R25, 0x00C0
	SBRS	R25, 5
	RJMP	__usendz_wait
	STS	0x00C6, R24
	RJMP	__usendz_loop
__usendz_done:
	RET

__str_0:
	.byte 69, 68, 71, 69, 0
	.balign 2
