; Generated by pymcuc for atmega328p
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ pymcu_hal__uart_avr__rx_buf, _stack_base + 0
.equ pymcu_hal__uart_avr__rx_head, _stack_base + 1
.equ pymcu_hal__uart_avr__rx_tail, _stack_base + 2
.equ pymcu_hal__timer_atmega328p__millis_count, _stack_base + 3
.equ inline2__delay_ms_avr_i, _stack_base + 18

.org 0x0000
.global main
	RJMP	main
pymcu_time__delay_1ms_avr:
    PUSH R24
    PUSH R25
    LDI R24, 21
_dly_outer_avr:
    LDI R25, 255
_dly_inner_avr:
    DEC R25
    BRNE _dly_inner_avr
    DEC R24
    BRNE _dly_outer_avr
    POP R25
    POP R24
	RET
main:
	LDI	R16, hi8(0x08FF)
	OUT	0x3E, R16
	LDI	R16, lo8(0x08FF)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)
; main.py:12:     uart = UART(9600)
; main.py:27:     if casted == 42:
; main.py:31: 
	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24
; main.py:13:     uart.println("IINT")
	LDI	R30, lo8(__str_0)
	LDI	R31, hi8(__str_0)
	CALL	__uart_send_z
; main.py:41:         delay_ms(1000)
L_30:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_0
	RJMP	L_31
L_BR_SKIP_0:
	RJMP	L_30
L_31:
	LDI	R24, 10
	STS	0x00C6, R24
; main.py:16:     x: int = 100
	LDI	R24, 100
	LDI	R25, 0
	MOV	R8, R24
	MOV	R9, R25
; main.py:17:     y: int = 200
	LDI	R24, 200
	MOV	R10, R24
	MOV	R11, R25
; main.py:18:     z: int = x + y
	LDI	R24, 44
	LDI	R25, 1
	MOV	R12, R24
	MOV	R13, R25
; main.py:19:     if z == 300:
	LDI	R18, 44
	LDI	R19, 1
	CP	R24, R18
	CPC	R25, R19
	BREQ	L_BR_SKIP_1
	RJMP	L_33
L_BR_SKIP_1:
; main.py:20:         uart.println("A:PASS")
	LDI	R30, lo8(__str_1)
	LDI	R31, hi8(__str_1)
	CALL	__uart_send_z
; main.py:41:         delay_ms(1000)
L_39:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_2
	RJMP	L_40
L_BR_SKIP_2:
	RJMP	L_39
L_40:
	LDI	R24, 10
	STS	0x00C6, R24
	RJMP	L_32
L_33:
; main.py:22:         uart.println("A:FAIL")
	LDI	R30, lo8(__str_2)
	LDI	R31, hi8(__str_2)
	CALL	__uart_send_z
; main.py:41:         delay_ms(1000)
L_46:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_3
	RJMP	L_47
L_BR_SKIP_3:
	RJMP	L_46
L_47:
	LDI	R24, 10
	STS	0x00C6, R24
L_32:
; main.py:25:     raw: int = 42
	LDI	R24, 42
	LDI	R25, 0
	MOV	R14, R24
	MOV	R15, R25
; main.py:26:     casted: int = int(raw)
	CALL	int
	MOV	R4, R24
	MOV	R5, R25
; main.py:27:     if casted == 42:
	LDI	R18, 42
	LDI	R19, 0
	CP	R24, R18
	CPC	R25, R19
	BREQ	L_BR_SKIP_4
	RJMP	L_49
L_BR_SKIP_4:
; main.py:28:         uart.println("B:PASS")
	LDI	R30, lo8(__str_3)
	LDI	R31, hi8(__str_3)
	CALL	__uart_send_z
; main.py:41:         delay_ms(1000)
L_55:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_5
	RJMP	L_56
L_BR_SKIP_5:
	RJMP	L_55
L_56:
	LDI	R24, 10
	STS	0x00C6, R24
	RJMP	L_48
L_49:
; main.py:30:         uart.println("B:FAIL")
	LDI	R30, lo8(__str_4)
	LDI	R31, hi8(__str_4)
	CALL	__uart_send_z
; main.py:41:         delay_ms(1000)
L_62:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_6
	RJMP	L_63
L_BR_SKIP_6:
	RJMP	L_62
L_63:
	LDI	R24, 10
	STS	0x00C6, R24
L_48:
; main.py:33:     neg: int = 0
	LDI	R24, 0
	LDI	R25, 0
	MOV	R6, R24
	MOV	R7, R25
; main.py:34:     neg = neg - 1
	LDI	R24, 255
	LDI	R25, 255
	MOV	R6, R24
	MOV	R7, R25
; main.py:35:     if neg == -1:
	CPI	R24, 255
	BREQ	L_BR_SKIP_7
	RJMP	L_65
L_BR_SKIP_7:
; main.py:36:         uart.println("C:PASS")
	LDI	R30, lo8(__str_5)
	LDI	R31, hi8(__str_5)
	CALL	__uart_send_z
; main.py:41:         delay_ms(1000)
L_71:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_8
	RJMP	L_72
L_BR_SKIP_8:
	RJMP	L_71
L_72:
	LDI	R24, 10
	STS	0x00C6, R24
	RJMP	L_64
L_65:
; main.py:38:         uart.println("C:FAIL")
	LDI	R30, lo8(__str_6)
	LDI	R31, hi8(__str_6)
	CALL	__uart_send_z
; main.py:41:         delay_ms(1000)
L_78:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_BR_SKIP_9
	RJMP	L_79
L_BR_SKIP_9:
	RJMP	L_78
L_79:
	LDI	R24, 10
	STS	0x00C6, R24
L_64:
; main.py:40:     while True:
L_80:
; main.py:41:         delay_ms(1000)
; main.py:21:     else:
; main.py:30:         uart.println("B:FAIL")
	LDI	R24, 0
	LDI	R25, 0
	STD	Y+18, R24
	STD	Y+19, R25
L_84:
	LDD	R24, Y+18
	LDD	R25, Y+19
	LDI	R18, 232
	LDI	R19, 3
	CP	R24, R18
	CPC	R25, R19
	BRLO	L_BR_SKIP_10
	RJMP	L_85
L_BR_SKIP_10:
	CALL	pymcu_time__delay_1ms_avr
	LDD	R24, Y+18
	LDD	R25, Y+19
	ADIW	R24, 1
	STD	Y+18, R24
	STD	Y+19, R25
	RJMP	L_84
L_85:
	RJMP	L_80
	RET

; --- Flash String Pool (LPM+Z UART send) ---
__uart_send_z:
__usendz_loop:
	LPM	R24, Z+
	TST	R24
	BREQ	__usendz_done
__usendz_wait:
	LDS	R25, 0x00C0
	SBRS	R25, 5
	RJMP	__usendz_wait
	STS	0x00C6, R24
	RJMP	__usendz_loop
__usendz_done:
	RET

__str_0:
	.byte 73, 73, 78, 84, 0
	.balign 2
__str_1:
	.byte 65, 58, 80, 65, 83, 83, 0
	.balign 2
__str_2:
	.byte 65, 58, 70, 65, 73, 76, 0
	.balign 2
__str_3:
	.byte 66, 58, 80, 65, 83, 83, 0
	.balign 2
__str_4:
	.byte 66, 58, 70, 65, 73, 76, 0
	.balign 2
__str_5:
	.byte 67, 58, 80, 65, 83, 83, 0
	.balign 2
__str_6:
	.byte 67, 58, 70, 65, 73, 76, 0
	.balign 2
